### ISSUE TITLE
Is navi usable with evil?

### ISSUE THREAD

**Issue by NightMachinery** [alphapapa/navi#12]
I have tried using navi, but going to the insert mode or disabling evil locally using `evil-local-mode` don't seem to work. Pressing numbers keeps either inserting them or becoming `C-u <number>`. `navi-cease-edit` doesn't seem to do anything.

**Comment by alphapapa** [comment]
Hello,

I don't use EVIL and I can't help you with it.  Anything should be usable with it given the proper customization.  See, e.g. the package `evil-collection`.
