### ISSUE TITLE
navi-regexp-quote-line-at-point causes 'Args out of range' when cursor at the end of navi buffer

### ISSUE THREAD

**Issue by smallid** [alphapapa/navi#3]
In the navi buffer the cursor is allowed past the last header displayed. When the cursor is in this position and a command is triggered such as 'show level 2' then **navi-regexp-quote-line-at-point** will cause an 'Args out of range' error. This appears to be because the function is using sub-string-no-properties with a point that is just past the end of the buffer string. 

The last header displayed in the navi buffer has further lines after it in the linked buffer, so the header line itself includes a newline character that navi copies and this seems to be why the cursor is allowed to go to the next (blank) line in the navi buffer. 

I'm not sure how this should properly be handled, but the following modification to the function to add error handling and a default value if there is an error (seems to be a effective workaround:

```
  (defun navi-regexp-quote-line-at-point ()
   "Store a quoted regexp for line at point.
   Leading and trailing whitespace is deleted."
     (condition-case nil
       (regexp-quote
         (outshine-chomp
           (substring-no-properties
             (buffer-string) (point-at-bol) (point-at-eol))))
       (error "10000: EOF")))
```

Note that I'm using navi-mode with an org buffer using outshine and outorg, and I'm also running the spacemacs package collection.

**Comment by alphapapa** [comment]
Thanks for reporting.  I'll try to fix it soon.

**Comment by alphapapa** [comment]
I just pushed a fix for this.  I tested it and it works for me.  Please let me know if it fixes it for you.  Thanks.

**Comment by smallid** [comment]
After fetching the new package version and removing my workarounds the issue is fixed. Thank you!
